In [43]:
import pandas as pd

In [44]:
data = pd.read_csv('../fourth_downs_2018_2019.csv')

/tmp/ipykernel_5344/2015066739.py:1: DtypeWarning: Columns (0: lateral_receiver_player_id, 1: lateral_receiver_player_name, 2: lateral_punt_returner_player_id, 3: lateral_punt_returner_player_name, 4: qb_hit_2_player_id, 5: qb_hit_2_player_name, 6: pass_defense_2_player_id, 7: pass_defense_2_player_name, 8: fumbled_2_player_id, 9: fumbled_2_player_name, 10: fumbled_2_team, 11: fumble_recovery_2_team, 12: fumble_recovery_2_player_id, 13: fumble_recovery_2_player_name, 14: half_sack_1_player_id, 15: half_sack_1_player_name, 16: half_sack_2_player_id, 17: half_sack_2_player_name, 18: safety_player_name, 19: safety_player_id, 20: end_clock_time) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../fourth_downs_2018_2019.csv')

In [45]:
# Columns of Interest
# 'home_team', 'away_team', 'posteam', 'defteam', 'td_team',
# 'penalty_team', 'return_team', 'fumbled_1_team', 'fumble_recovery_1_team',

In [46]:
for c in data.columns:
    print(c)

play_id
game_id
old_game_id
home_team
away_team
season_type
week
posteam
posteam_type
defteam
side_of_field
yardline_100
game_date
quarter_seconds_remaining
half_seconds_remaining
game_seconds_remaining
game_half
quarter_end
drive
sp
qtr
down
goal_to_go
time
yrdln
ydstogo
ydsnet
desc
play_type
yards_gained
shotgun
no_huddle
qb_dropback
qb_kneel
qb_spike
qb_scramble
pass_length
pass_location
air_yards
yards_after_catch
run_location
run_gap
field_goal_result
kick_distance
extra_point_result
two_point_conv_result
home_timeouts_remaining
away_timeouts_remaining
timeout
timeout_team
td_team
td_player_name
td_player_id
posteam_timeouts_remaining
defteam_timeouts_remaining
total_home_score
total_away_score
posteam_score
defteam_score
score_differential
posteam_score_post
defteam_score_post
score_differential_post
no_score_prob
opp_fg_prob
opp_safety_prob
opp_td_prob
fg_prob
safety_prob
td_prob
extra_point_prob
two_point_conversion_prob
ep
epa
total_home_epa
total_away_epa
total_home_rush_epa
total_away_rush_epa
total_home_pass_epa
total_away_pass_epa
air_epa
yac_epa
comp_air_epa
comp_yac_epa
total_home_comp_air_epa
total_away_comp_air_epa
total_home_comp_yac_epa
total_away_comp_yac_epa
total_home_raw_air_epa
total_away_raw_air_epa
total_home_raw_yac_epa
total_away_raw_yac_epa
wp
def_wp
home_wp
away_wp
wpa
vegas_wpa
vegas_home_wpa
home_wp_post
away_wp_post
vegas_wp
vegas_home_wp
total_home_rush_wpa
total_away_rush_wpa
total_home_pass_wpa
total_away_pass_wpa
air_wpa
yac_wpa
comp_air_wpa
comp_yac_wpa
total_home_comp_air_wpa
total_away_comp_air_wpa
total_home_comp_yac_wpa
total_away_comp_yac_wpa
total_home_raw_air_wpa
total_away_raw_air_wpa
total_home_raw_yac_wpa
total_away_raw_yac_wpa
punt_blocked
first_down_rush
first_down_pass
first_down_penalty
third_down_converted
third_down_failed
fourth_down_converted
fourth_down_failed
incomplete_pass
touchback
interception
punt_inside_twenty
punt_in_endzone
punt_out_of_bounds
punt_downed
punt_fair_catch
kickoff_inside_twenty
kickoff_in_endzone
kickoff_out_of_bounds
kickoff_downed
kickoff_fair_catch
fumble_forced
fumble_not_forced
fumble_out_of_bounds
solo_tackle
safety
penalty
tackled_for_loss
fumble_lost
own_kickoff_recovery
own_kickoff_recovery_td
qb_hit
rush_attempt
pass_attempt
sack
touchdown
pass_touchdown
rush_touchdown
return_touchdown
extra_point_attempt
two_point_attempt
field_goal_attempt
kickoff_attempt
punt_attempt
fumble
complete_pass
assist_tackle
lateral_reception
lateral_rush
lateral_return
lateral_recovery
passer_player_id
passer_player_name
passing_yards
receiver_player_id
receiver_player_name
receiving_yards
rusher_player_id
rusher_player_name
rushing_yards
lateral_receiver_player_id
lateral_receiver_player_name
lateral_receiving_yards
lateral_rusher_player_id
lateral_rusher_player_name
lateral_rushing_yards
lateral_sack_player_id
lateral_sack_player_name
interception_player_id
interception_player_name
lateral_interception_player_id
lateral_interception_player_name
punt_returner_player_id
punt_returner_player_name
lateral_punt_returner_player_id
lateral_punt_returner_player_name
kickoff_returner_player_name
kickoff_returner_player_id
lateral_kickoff_returner_player_id
lateral_kickoff_returner_player_name
punter_player_id
punter_player_name
kicker_player_name
kicker_player_id
own_kickoff_recovery_player_id
own_kickoff_recovery_player_name
blocked_player_id
blocked_player_name
tackle_for_loss_1_player_id
tackle_for_loss_1_player_name
tackle_for_loss_2_player_id
tackle_for_loss_2_player_name
qb_hit_1_player_id
qb_hit_1_player_name
qb_hit_2_player_id
qb_hit_2_player_name
forced_fumble_player_1_team
forced_fumble_player_1_player_id
forced_fumble_player_1_player_name
forced_fumble_player_2_team
forced_fumble_player_2_player_id
forced_fumble_player_2_player_name
solo_tackle_1_team
solo_tackle_2_team
solo_tackle_1_player_id
solo_tackle_2_player_id
solo_tackle_1_player_name
solo_tackle_2_player_name
assist_tackle_1_player_id
assist_tackle_1_player_name
assist_tackle_1_team
assist_tackle_2_player_id
assist_tackle_2_player_name
assist_tackle_2_team
assist_tackle_3_player_id
assist_tackle_3_player_name
assist_tackle_3_team
assist_tackle_4_player_id
assist_tackle_4_player_name
assist_tackle_4_team
tackle_with_assist
tackle_with_assist_1_player_id
tackle_with_assist_1_player_name
tackle_with_assist_1_team
tackle_with_assist_2_player_id
tackle_with_assist_2_player_name
tackle_with_assist_2_team
pass_defense_1_player_id
pass_defense_1_player_name
pass_defense_2_player_id
pass_defense_2_player_name
fumbled_1_team
fumbled_1_player_id
fumbled_1_player_name
fumbled_2_player_id
fumbled_2_player_name
fumbled_2_team
fumble_recovery_1_team
fumble_recovery_1_yards
fumble_recovery_1_player_id
fumble_recovery_1_player_name
fumble_recovery_2_team
fumble_recovery_2_yards
fumble_recovery_2_player_id
fumble_recovery_2_player_name
sack_player_id
sack_player_name
half_sack_1_player_id
half_sack_1_player_name
half_sack_2_player_id
half_sack_2_player_name
return_team
return_yards
penalty_team
penalty_player_id
penalty_player_name
penalty_yards
replay_or_challenge
replay_or_challenge_result
penalty_type
defensive_two_point_attempt
defensive_two_point_conv
defensive_extra_point_attempt
defensive_extra_point_conv
safety_player_name
safety_player_id
season
cp
cpoe
series
series_success
series_result
order_sequence
start_time
time_of_day
stadium
weather
nfl_api_id
play_clock
play_deleted
play_type_nfl
special_teams_play
st_play_type
end_clock_time
end_yard_line
fixed_drive
fixed_drive_result
drive_real_start_time
drive_play_count
drive_time_of_possession
drive_first_downs
drive_inside20
drive_ended_with_score
drive_quarter_start
drive_quarter_end
drive_yards_penalized
drive_start_transition
drive_end_transition
drive_game_clock_start
drive_game_clock_end
drive_start_yard_line
drive_end_yard_line
drive_play_id_started
drive_play_id_ended
away_score
home_score
location
result
total
spread_line
total_line
div_game
roof
surface
temp
wind
home_coach
away_coach
stadium_id
game_stadium
aborted_play
success
passer
passer_jersey_number
rusher
rusher_jersey_number
receiver
receiver_jersey_number
pass
rush
first_down
special
play
passer_id
rusher_id
receiver_id
name
jersey_number
id
fantasy_player_name
fantasy_player_id
fantasy
fantasy_id
out_of_bounds
home_opening_kickoff
qb_epa
xyac_epa
xyac_mean_yardage
xyac_median_yardage
xyac_success
xyac_fd
xpass
pass_oe

In [47]:
## Select only the columns of interest to test functionality
columns_of_interest = ['posteam', 'defteam', 'home_team', 'away_team', 'touchdown', 'penalty', 'fumble', 'td_team',
                       'penalty_team', 'return_team', 'fumbled_1_team', 'fumble_recovery_1_team']
data_subset = data[columns_of_interest]
data_subset.head()

,posteam,defteam,home_team,away_team,touchdown,...,td_team,penalty_team,return_team,fumbled_1_team,fumble_recovery_1_team
0,ATL,PHI,PHI,ATL,0.0,...,NaN,NaN,NaN,NaN,NaN
1,PHI,ATL,PHI,ATL,0.0,...,NaN,PHI,ATL,NaN,NaN
2,ATL,PHI,PHI,ATL,0.0,...,NaN,NaN,NaN,NaN,NaN
3,PHI,ATL,PHI,ATL,0.0,...,NaN,NaN,ATL,NaN,NaN
4,ATL,PHI,PHI,ATL,0.0,...,NaN,NaN,PHI,NaN,NaN

In [48]:
## Create new columns: home_is_posteam, td_is_posteam, penalty_is_posteam, return_is_posteam, fumble_is_posteam as 0 or 1
data_subset['home_is_posteam'] = (data_subset['home_team'] == data_subset['posteam']).astype(int)
data_subset['td_is_posteam'] = (data_subset['td_team'] == data_subset['posteam']).astype(int)
data_subset['penalty_is_posteam'] = (data_subset['penalty_team'] == data_subset['posteam']).astype(int)
data_subset['return_is_posteam'] = (data_subset['return_team'] == data_subset['posteam']).astype(int)
data_subset['fumble_is_posteam'] = (data_subset['fumbled_1_team'] == data_subset['posteam']).astype(int)
data_subset.head()

,posteam,defteam,home_team,away_team,touchdown,...,home_is_posteam,td_is_posteam,penalty_is_posteam,return_is_posteam,fumble_is_posteam
0,ATL,PHI,PHI,ATL,0.0,...,0,0,0,0,0
1,PHI,ATL,PHI,ATL,0.0,...,1,0,1,0,0
2,ATL,PHI,PHI,ATL,0.0,...,0,0,0,0,0
3,PHI,ATL,PHI,ATL,0.0,...,1,0,0,0,0
4,ATL,PHI,PHI,ATL,0.0,...,0,0,0,0,0

In [49]:
## Drop the old irrelevant columns
data_subset = data_subset.drop(columns=['home_team', 'away_team', 'td_team',
                                       'penalty_team', 'return_team', 'fumbled_1_team', 'fumble_recovery_1_team'])
data_subset.head()

,posteam,defteam,touchdown,penalty,fumble,home_is_posteam,td_is_posteam,penalty_is_posteam,return_is_posteam,fumble_is_posteam
0,ATL,PHI,0.0,0.0,0.0,0,0,0,0,0
1,PHI,ATL,0.0,1.0,0.0,1,0,1,0,0
2,ATL,PHI,0.0,0.0,0.0,0,0,0,0,0
3,PHI,ATL,0.0,0.0,0.0,1,0,0,0,0
4,ATL,PHI,0.0,0.0,0.0,0,0,0,0,0

In [50]:
## Rewrite logic as a function that can be universally applied to any team column
def create_is_posteam_column(df, team_col):
    """
    This function takes in a dataframe and a team column name, creates a new column indicating whether the team in the specified column is the same as the posteam, and drops the old team column.
    Args:
        df (pd.DataFrame): The input dataframe.
        team_col (str): The name of the team column to compare with posteam.
    Returns:
        pd.DataFrame: The modified dataframe with the new is_posteam column and the old team column dropped.
    Example:
        df = create_is_posteam_column(df, 'home_team')
        Result would be df, with the new column 'home_is_posteam' and the old 'home_team' column dropped.
    """
    new_col_name = team_col.replace('_team', '_is_posteam')
    df[new_col_name] = (df[team_col] == df['posteam']).astype(int)
    ## Drop old team column
    df = df.drop(columns=[team_col])
    return df

In [51]:
## Test function on copy of original data
pd.set_option('display.max_columns', 10)  # Ensure all columns are displayed
data_test = data.copy()
data_test = create_is_posteam_column(data_test, 'home_team')
## Look at posteam, away_team, and home_is_posteam columns to verify functionality
data_test[['posteam', 'away_team', 'home_is_posteam']].head()

  posteam away_team  home_is_posteam
0     ATL       ATL                0
1     PHI       ATL                1
2     ATL       ATL                0
3     PHI       ATL                1
4     ATL       ATL                0